# Generated by Django 2.0.4 on 2018-04-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollhighschool',
            name='year',
            field=models.IntegerField(),
        ),
    ]
