# Generated by Django 2.0.4 on 2018-04-20 12:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20180420_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollhighschool',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 20, 12, 8, 54, 339809, tzinfo=utc), help_text='수정일'),
        ),
        migrations.AddField(
            model_name='enrollhighschool',
            name='deleted_at',
            field=models.DateTimeField(help_text='수정일', null=True),
        ),
        migrations.AddField(
            model_name='enrollhighschool',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 20, 12, 8, 54, 339844, tzinfo=utc), help_text='수정일', null=True),
        ),
        migrations.AlterField(
            model_name='enrollhighschool',
            name='art',
            field=models.FloatField(help_text="진학자 특수목적고 예고체고'"),
        ),
        migrations.AlterField(
            model_name='enrollhighschool',
            name='characterization',
            field=models.FloatField(help_text='진학자 특성화고'),
        ),
        migrations.AlterField(
            model_name='enrollhighschool',
            name='data_type',
            field=models.CharField(help_text='수정일', max_length=5),
        ),
        migrations.AlterField(
            model_name='enrollhighschool',
            name='etc',
            field=models.FloatField(help_text="진학자 기타'"),
        ),
        migrations.AlterField(
            model_name='enrollhighschool',
            name='foreigner',
            field=models.FloatField(help_text="진학자 특수목적고 외고국제고'"),
        ),
        migrations.AlterField(
            model_name='enrollhighschool',
            name='general',
            field=models.FloatField(help_text="진학자 일반고'"),
        ),
        migrations.AlterField(
            model_name='enrollhighschool',
            name='graduate',
            field=models.FloatField(help_text='졸업자'),
        ),
        migrations.AlterField(
            model_name='enrollhighschool',
            name='jibun',
            field=models.CharField(help_text='지번 주소', max_length=50),
        ),
        migrations.AlterField(
            model_name='enrollhighschool',
            name='job',
            field=models.FloatField(help_text='취업자'),
        ),
        migrations.AlterField(
            model_name='enrollhighschool',
            name='meister',
            field=models.FloatField(help_text="진학자 특수목적고 마이스터고'"),
        ),
        migrations.AlterField(
            model_name='enrollhighschool',
            name='nothing',
            field=models.FloatField(help_text='무직 및 미상'),
        ),
        migrations.AlterField(
            model_name='enrollhighschool',
            name='private',
            field=models.FloatField(help_text="진학자 자율고 자율형사립고'"),
        ),
        migrations.AlterField(
            model_name='enrollhighschool',
            name='public',
            field=models.FloatField(help_text="진학자 자율고 자율형공립고'"),
        ),
        migrations.AlterField(
            model_name='enrollhighschool',
            name='region_code',
            field=models.CharField(help_text='지역코드', max_length=50),
        ),
        migrations.AlterField(
            model_name='enrollhighschool',
            name='road',
            field=models.CharField(help_text='도로명 주소', max_length=50),
        ),
        migrations.AlterField(
            model_name='enrollhighschool',
            name='school_code',
            field=models.CharField(help_text='학교코드', max_length=50),
        ),
        migrations.AlterField(
            model_name='enrollhighschool',
            name='science',
            field=models.FloatField(help_text="진학자 특수목적고 과학고'"),
        ),
        migrations.AlterField(
            model_name='enrollhighschool',
            name='year',
            field=models.IntegerField(help_text='년도'),
        ),
    ]
