# Generated by Django 2.0.4 on 2018-04-20 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20180420_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollhighschool',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='수정일'),
        ),
        migrations.AlterField(
            model_name='enrollhighschool',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='수정일', null=True),
        ),
    ]
