# Generated by Django 2.0.4 on 2018-04-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20180420_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollhighschool',
            name='school_name',
            field=models.CharField(default='', help_text='학교명', max_length=50),
        ),
    ]
