# Generated by Django 2.0.4 on 2018-04-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='deleted_at',
            field=models.DateTimeField(null=True, verbose_name='date deleted'),
        ),
        migrations.AlterField(
            model_name='token',
            name='updated_at',
            field=models.DateTimeField(null=True, verbose_name='date updated'),
        ),
    ]
