# Generated by Django 2.0.4 on 2018-04-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sido', models.CharField(default='', help_text='시도', max_length=50)),
                ('sigungu', models.CharField(default='', help_text='시군구', max_length=50)),
                ('administration', models.CharField(default='', help_text='행정구역명', max_length=50)),
                ('administration_name', models.CharField(default='', help_text='행정동', max_length=50)),
                ('legal_name', models.CharField(default='', help_text='법정동', max_length=50)),
                ('administration_category', models.IntegerField(default='', help_text='행정구역분류', max_length=50)),
                ('administration_code', models.IntegerField(default='', help_text='행정기관코드', max_length=50)),
                ('legal_code', models.IntegerField(default='', help_text='법정동코드', max_length=50)),
                ('admin', models.CharField(default='', help_text='관할지역', max_length=50, null=True)),
                ('english_administration_name', models.CharField(default='', help_text='행정동 영문명칭', max_length=50)),
                ('memo', models.TextField(help_text='비고')),
            ],
        ),
    ]
