# Generated by Django 2.0.4 on 2018-04-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0002_auto_20180422_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sido', models.CharField(default='', help_text='시도', max_length=50)),
                ('sigungu', models.CharField(default='', help_text='시군구', max_length=50)),
                ('administration', models.CharField(default='', help_text='행정구역명', max_length=50)),
                ('administration_name', models.CharField(default='', help_text='행정동', max_length=50)),
                ('legal_name', models.CharField(default='', help_text='법정동', max_length=50)),
                ('administration_category', models.IntegerField(help_text='행정구역분류')),
                ('administration_code', models.IntegerField(help_text='행정기관코드', unique=True)),
                ('legal_code', models.IntegerField(help_text='법정동코드', unique=True)),
                ('admin', models.CharField(default='', help_text='관할지역', max_length=50, null=True)),
                ('english_administration_name', models.CharField(default='', help_text='행정동 영문명칭', max_length=50)),
                ('memo', models.TextField(help_text='비고')),
            ],
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
