# Generated by Django 2.0.4 on 2018-04-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0003_auto_20180422_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='administration_code',
            field=models.IntegerField(help_text='행정기관코드'),
        ),
        migrations.AlterField(
            model_name='code',
            name='legal_code',
            field=models.IntegerField(help_text='법정동코드'),
        ),
        migrations.AlterUniqueTogether(
            name='code',
            unique_together={('administration_code', 'administration_name'), ('legal_code', 'legal_name')},
        ),
    ]
