# Generated by Django 2.0.4 on 2018-04-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0006_auto_20180422_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='administration_category',
            field=models.CharField(help_text='행정구역분류', max_length=50),
        ),
    ]
